version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    networks:
      - spring-mysql-net
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: user_management
      MYSQL_USER: masterdb
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    networks:
      - spring-mysql-net
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

networks:
  spring-mysql-net: